# Form implementation generated from reading ui file 'budgetDemo.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(544, 361)
        self.labelPrompt = QtWidgets.QLabel(parent=Dialog)
        self.labelPrompt.setGeometry(QtCore.QRect(160, 20, 251, 16))
        self.labelPrompt.setObjectName("labelPrompt")
        self.labelAmount = QtWidgets.QLabel(parent=Dialog)
        self.labelAmount.setGeometry(QtCore.QRect(50, 70, 181, 16))
        self.labelAmount.setObjectName("labelAmount")
        self.lineEditAmount = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditAmount.setGeometry(QtCore.QRect(232, 70, 201, 21))
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.labelNeed = QtWidgets.QLabel(parent=Dialog)
        self.labelNeed.setGeometry(QtCore.QRect(60, 200, 151, 16))
        self.labelNeed.setObjectName("labelNeed")
        self.labelWant = QtWidgets.QLabel(parent=Dialog)
        self.labelWant.setGeometry(QtCore.QRect(60, 240, 151, 16))
        self.labelWant.setObjectName("labelWant")
        self.labelSavings = QtWidgets.QLabel(parent=Dialog)
        self.labelSavings.setGeometry(QtCore.QRect(60, 280, 151, 16))
        self.labelSavings.setObjectName("labelSavings")
        self.labelNeedAmount = QtWidgets.QLabel(parent=Dialog)
        self.labelNeedAmount.setGeometry(QtCore.QRect(280, 200, 191, 16))
        self.labelNeedAmount.setObjectName("labelNeedAmount")
        self.labelWantAmount = QtWidgets.QLabel(parent=Dialog)
        self.labelWantAmount.setGeometry(QtCore.QRect(280, 240, 191, 16))
        self.labelWantAmount.setObjectName("labelWantAmount")
        self.labelSavingAmount = QtWidgets.QLabel(parent=Dialog)
        self.labelSavingAmount.setGeometry(QtCore.QRect(280, 280, 191, 16))
        self.labelSavingAmount.setObjectName("labelSavingAmount")
        self.pushButtonCalculate = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(330, 120, 100, 32))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.labelAmount.setBuddy(self.lineEditAmount)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelPrompt.setText(_translate("Dialog", "Determine Budget Percentages"))
        self.labelAmount.setText(_translate("Dialog", "Enter Total Amount"))
        self.labelNeed.setText(_translate("Dialog", "Need Amount (50%)"))
        self.labelWant.setText(_translate("Dialog", "Want Amount (30%)"))
        self.labelSavings.setText(_translate("Dialog", "Savings Amount (20%)"))
        self.labelNeedAmount.setText(_translate("Dialog", "TextLabel"))
        self.labelWantAmount.setText(_translate("Dialog", "TextLabel"))
        self.labelSavingAmount.setText(_translate("Dialog", "TextLabel"))
        self.pushButtonCalculate.setText(_translate("Dialog", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
