# Form implementation generated from reading ui file 'pomodoroDemo.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButtonStart = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonStart.setGeometry(QtCore.QRect(50, 230, 100, 32))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.pushButtonReset = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonReset.setGeometry(QtCore.QRect(250, 230, 100, 32))
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=Dialog)
        self.lcdNumber.setGeometry(QtCore.QRect(30, 50, 341, 151))
        self.lcdNumber.setObjectName("lcdNumber")
        self.labelName = QtWidgets.QLabel(parent=Dialog)
        self.labelName.setGeometry(QtCore.QRect(37, 10, 331, 20))
        self.labelName.setText("")
        self.labelName.setObjectName("labelName")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonStart.setText(_translate("Dialog", "Start"))
        self.pushButtonReset.setText(_translate("Dialog", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
