# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 349)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 551, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxThursday = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.checkBoxThursday.setObjectName("checkBoxThursday")
        self.gridLayout.addWidget(self.checkBoxThursday, 2, 4, 1, 1)
        self.checkBoxWednesday = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.checkBoxWednesday.setObjectName("checkBoxWednesday")
        self.gridLayout.addWidget(self.checkBoxWednesday, 2, 3, 1, 1)
        self.checkBoxTuesday = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.checkBoxTuesday.setObjectName("checkBoxTuesday")
        self.gridLayout.addWidget(self.checkBoxTuesday, 2, 2, 1, 1)
        self.checkBoxSunday = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.checkBoxSunday.setObjectName("checkBoxSunday")
        self.gridLayout.addWidget(self.checkBoxSunday, 2, 7, 1, 1)
        self.checkBoxMonday = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.checkBoxMonday.setObjectName("checkBoxMonday")
        self.gridLayout.addWidget(self.checkBoxMonday, 2, 1, 1, 1)
        self.spinBoxHoliday = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.spinBoxHoliday.setObjectName("spinBoxHoliday")
        self.gridLayout.addWidget(self.spinBoxHoliday, 3, 2, 1, 2)
        self.checkBoxFriday = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.checkBoxFriday.setObjectName("checkBoxFriday")
        self.gridLayout.addWidget(self.checkBoxFriday, 2, 5, 1, 1)
        self.checkBoxSaturday = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.checkBoxSaturday.setObjectName("checkBoxSaturday")
        self.gridLayout.addWidget(self.checkBoxSaturday, 2, 6, 1, 1)
        self.labelWorkDays = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelWorkDays.setObjectName("labelWorkDays")
        self.gridLayout.addWidget(self.labelWorkDays, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 2)
        self.spinBoxWordCount = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.spinBoxWordCount.setObjectName("spinBoxWordCount")
        self.gridLayout.addWidget(self.spinBoxWordCount, 0, 4, 1, 4)
        self.labelWordCount = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelWordCount.setObjectName("labelWordCount")
        self.gridLayout.addWidget(self.labelWordCount, 0, 0, 1, 3)
        self.labelResult = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.gridLayout.addWidget(self.labelResult, 4, 0, 1, 6)
        self.pushButtonCalculate = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.gridLayout.addWidget(self.pushButtonCalculate, 4, 6, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBoxThursday.setText(_translate("Dialog", "Th"))
        self.checkBoxWednesday.setText(_translate("Dialog", "W"))
        self.checkBoxTuesday.setText(_translate("Dialog", "T"))
        self.checkBoxSunday.setText(_translate("Dialog", "Su"))
        self.checkBoxMonday.setText(_translate("Dialog", "M"))
        self.checkBoxFriday.setText(_translate("Dialog", "F"))
        self.checkBoxSaturday.setText(_translate("Dialog", "S"))
        self.labelWorkDays.setText(_translate("Dialog", "Select Working Days:"))
        self.label.setText(_translate("Dialog", "Number of Public Holidays:"))
        self.labelWordCount.setText(_translate("Dialog", "Enter Total Words:"))
        self.pushButtonCalculate.setText(_translate("Dialog", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
